version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  ApplicationStop:
    - location: deploy_scripts/stop_server 
      timeout: 300
      runas: root
# During the BeforeInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  BeforeInstall:
    - location: deploy_scripts/install_dependecies
      timeout: 300
      runas: root
# During the AfterInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  AfterInstall:
    - location:     
      timeout: 
      runas:
# During the ApplicationInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ApplicationStart:
    - location: deploy_scripts/start_server 
      timeout: 300
      runas: root

